### ISSUE TITLE
convolve_2d race condition in removing file

### ISSUE THREAD

**Issue by dcdenu4** [natcap/pygeoprocessing#124]
A user working with the habitat quality model posting an interesting error from `convolve_2d` that looks like a race condition between removing `mask_raster_path`. The user post with the full output log is here: https://community.naturalcapitalproject.org/t/filenotfounderror-winerror-2/1408

```python
2020-10-10 00:13:36,506 geoprocessing.convolve_2d(2568) INFO convolution nodata normalize 100.0% complete on filtered_ag_per_c.tif
2020-10-10 00:13:37,047 model._logged_target(1632) ERROR Exception while executing <function execute at 0x1C221540>
Traceback (most recent call last):
  File "site-packages\natcap\invest\ui\model.py", line 1629, in _logged_target
  File "site-packages\natcap\invest\habitat_quality.py", line 531, in execute
  File "site-packages\pygeoprocessing\geoprocessing.py", line 2580, in convolve_2d
  File "shutil.py", line 516, in rmtree
  File "shutil.py", line 400, in _rmtree_unsafe
  File "shutil.py", line 398, in _rmtree_unsafe
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'C:\\Users\\RRomo\\AppData\\Local\\Temp\\tmpuwwh4_ng\\convolved_mask.tif'
2020-10-10 00:13:37,085 model._logged_target(1635) INFO Execution finished
2020-10-10 00:13:38,742 utils.prepare_workspace(117) INFO Elapsed time: 14h 7m 16.290000000000873s
```

The error looks related to this Python issue here: https://bugs.python.org/issue29699.

The user looks to have been using quite a large dataset as the convolution was running for **10+ hours** before failing.

**Comment by richpsharp** [comment]
Thanks Doug, I'll handle this and just guard against this type of error and log a warning if that's the case.
