### ISSUE TITLE
EPSG:54009 - World_Mollweide - Projected projection does not project to WGS84

### ISSUE THREAD

**Issue by richpsharp** [natcap/pygeoprocessing#169]
I get this error which must be related to sampling outside of the wgs84 space:

```
2021-02-26 10:28:53,926 (915) MainProcess DEBUG pygeoprocessing.geoprocessing [warp_raster:1928] transforming bounding box from [-18027854.13532489, -7965787.758948961, 18027101.85314211, 8828766.53043604]
2021-02-26 10:28:53,966 (955) MainProcess DEBUG pygeoprocessing.geoprocessing [warp_raster:1933] transforming bounding to [inf, -72.34178794591537, inf, inf]
Traceback (most recent call last):
  File "align_test.py", line 15, in <module>
    pygeoprocessing.warp_raster(
  File "C:\Users\Rich\Miniconda3\envs\py38\lib\site-packages\pygeoprocessing-2.1.3a1.post169+gd7a1efa.d20210212-py3.8-win-amd64.egg\pygeoprocessing\geoprocessing.py", line 1941, in warp_raster
    target_x_size = int(abs(
ValueError: cannot convert float NaN to integer
```

**Comment by richpsharp** [comment]
I think this is fixed by #177
