### ISSUE TITLE
Zonal stats logger callback format error

### ISSUE THREAD

**Issue by dcdenu4** [natcap/pygeoprocessing#182]
When I run `pgp.zonal_statistics` in a python script I see output similar to:

```python
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\workbench-py37\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\workbench-py37\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\workbench-py37\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\workbench-py37\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<stdin>", line 1, in <module>
Message: 'rasterizing polygon 3 of 21 set %.1f%% complete'
Arguments: (82.45, '')
```
On line 1339 in `pgp.zonal_statistics` a logger callback function is made with a message that has 1 floating point replacement spot. 
https://github.com/natcap/pygeoprocessing/blob/d8c7cab583d08d26f0d9230e7d0a12f944779526/src/pygeoprocessing/geoprocessing.py#L1339
```python
        rasterize_callback = _make_logger_callback(
            "rasterizing polygon " + str(set_index+1) + " of " +
            str(len(disjoint_fid_set)) + " set %.1f%% complete")
```
However, in the callback function `pgp._make_logger_callback` on line 3243 it expects 2 replacement spots. https://github.com/natcap/pygeoprocessing/blob/d8c7cab583d08d26f0d9230e7d0a12f944779526/src/pygeoprocessing/geoprocessing.py#L3243
```python
if p_progress_arg:
    LOGGER.info(message, df_complete * 100, p_progress_arg[0])
else:
    LOGGER.info(message, df_complete * 100, '')
```

**Comment by dcdenu4** [comment]
That message could just be missing a `%s` at the end of it. At least as indicated by other messages that use that function logger callback:
```
    reproject_callback = _make_logger_callback(
        "Warp %.1f%% complete %s")
...
    rasterize_callback = _make_logger_callback(
        "RasterizeLayer %.1f%% complete %s")

```
