### ISSUE TITLE
convolve_2d crashes if statistics can't compute in < 60s

### ISSUE THREAD

**Issue by phargogh** [natcap/pygeoprocessing#251]
We had a [case on the forums](https://community.naturalcapitalproject.org/t/habitat-quality-empty-results-no-output-data-folder/2616/6) where someone was running Habitat Quality on 1m x 1m pixels with a 15km `MAX_DIST` resulting in a kernel with a 15000 pixel radius.  This was then causing the following exception to occur in the logging:

```python
2022-03-22 21:58:52,913 (pygeoprocessing.geoprocessing) geoprocessing.convolve_2d(2678) INFO starting convolve
2022-03-22 22:00:16,184 (pygeoprocessing.geoprocessing) geoprocessing.convolve_2d(2696) DEBUG start fill work queue thread
2022-03-22 22:00:16,185 (pygeoprocessing.geoprocessing) geoprocessing._fill_work_queue(2700) DEBUG fill work queue
2022-03-22 22:00:16,185 (pygeoprocessing.geoprocessing) geoprocessing.convolve_2d(2714) DEBUG start worker thread
2022-03-22 22:00:16,187 (pygeoprocessing.geoprocessing) geoprocessing.convolve_2d(2726) INFO 23206701680 sent to workers, wait for worker results
2022-03-22 22:01:16,195 (taskgraph.Task) Task.add_task(706) ERROR Something went wrong when adding task convolve_exponential_c_amelh (10), terminating taskgraph.
Traceback (most recent call last):
  File "taskgraph\Task.py", line 674, in add_task
  File "taskgraph\Task.py", line 1093, in _call
  File "pygeoprocessing\geoprocessing.py", line 2730, in convolve_2d
  File "queue.py", line 178, in get
_queue.Empty
2022-03-22 22:01:16,217 (natcap.invest.utils) utils.prepare_workspace(167) ERROR Exception while executing Habitat-Quality
Traceback (most recent call last):
  File "natcap\invest\utils.py", line 165, in prepare_workspace
  File "natcap\invest\ui\model.py", line 1649, in _logged_target
  File "natcap\invest\habitat_quality.py", line 546, in execute
  File "taskgraph\Task.py", line 674, in add_task
  File "taskgraph\Task.py", line 1093, in _call
  File "pygeoprocessing\geoprocessing.py", line 2730, in convolve_2d
  File "queue.py", line 178, in get
_queue.Empty
```

Note the `23206701680 sent to workers, wait for worker results`.  The worker only sends a result back in the queue once the queue has been exhausted.  Also note that pygeoprocessing's `_MAX_TIMEOUT` is only set to wait for 60s.  I strongly suspect that this exception is being raised because we can't get through the queue in less than 60 seconds and so then the queue is empty when the timeout is raised.

This clearly only happens on super large rasters, but it's still a bug.

**Comment by phargogh** [comment]
Duplicate of #360
