### ISSUE TITLE
calculate_subwatershed_boundary TypeError given a NoneType argument

### ISSUE THREAD

**Issue by davemfish** [natcap/pygeoprocessing#363]
```
(C:\Users\dmf\projects\invest\env) λ invest -vvv run routedem -d data\invest-sample-data\RouteDEM\routedem_gura.invs.json -w ../scratch/routedem2
12/11/2023 16:32:17  natcap.invest.cli  INFO     Imported target natcap.invest.routedem from <module 'natcap.invest.routedem' from 'C:\\Users\\dmf\\projects\\invest\\env\\lib\\site-packages\\natcap\\invest\\routedem.py'>
12/11/2023 16:32:17  natcap.invest.utils Level 100 Writing log messages to [../scratch/routedem2\InVEST-natcap.invest.routedem-log-2023-12-11--16_32_17.txt]
12/11/2023 16:32:17  natcap.invest.cli  Level 100 Starting model with parameters:
Arguments for InVEST natcap.invest.routedem 3.13.0.post775+gf7597fa27:
algorithm                     D8
calculate_downstream_distance False
calculate_flow_accumulation   True
calculate_flow_direction      True
calculate_slope               True
calculate_stream_order        True
calculate_stream_threshold    True
calculate_subwatersheds       True
dem_band_index
dem_path                      C:\Users\dmf\projects\invest\data\invest-sample-data\RouteDEM\DEM_gura.tif
results_suffix                gura
threshold_flow_accumulation   1000
workspace_dir                 ../scratch/routedem2

12/11/2023 16:32:17  natcap.invest.routedem INFO     Using DEM band index 1
12/11/2023 16:32:18  pygeoprocessing.routing.routing INFO     (fill pits): complete
12/11/2023 16:32:18  natcap.invest.routedem INFO     calculating flow direction
12/11/2023 16:32:18  pygeoprocessing.routing.routing INFO     (flow dir d8): complete
12/11/2023 16:32:18  natcap.invest.routedem INFO     calculating flow accumulation
12/11/2023 16:32:19  pygeoprocessing.routing.routing INFO     Flow accumulation D8 100.0% complete
12/11/2023 16:32:19  pygeoprocessing.geoprocessing INFO     starting stats_worker
12/11/2023 16:32:19  pygeoprocessing.geoprocessing_core DEBUG    stats worker PID: 3188
12/11/2023 16:32:19  pygeoprocessing.geoprocessing INFO     started stats_worker <Thread(Thread-1 (stats_worker), started daemon 21176)>
12/11/2023 16:32:19  pygeoprocessing.geoprocessing INFO     100.0% complete
12/11/2023 16:32:19  pygeoprocessing.geoprocessing INFO     Waiting for raster stats worker result.
12/11/2023 16:32:19  pygeoprocessing.routing.routing INFO     (extract_strahler_streams_d8): seed the drains
12/11/2023 16:32:19  pygeoprocessing.routing.routing INFO     (extract_strahler_streams_d8): drain seeding complete
12/11/2023 16:32:19  pygeoprocessing.routing.routing INFO     (extract_strahler_streams_d8): starting upstream walk
12/11/2023 16:32:19  pygeoprocessing.routing.routing INFO     (extract_strahler_streams_d8): stream segment creation complete
12/11/2023 16:32:19  pygeoprocessing.routing.routing INFO     (extract_strahler_streams_d8): determining stream order
12/11/2023 16:32:19  pygeoprocessing.routing.routing INFO     (extract_strahler_streams_d8): stream order processing complete
12/11/2023 16:32:19  pygeoprocessing.routing.routing INFO     (extract_strahler_streams_d8): determine rivers
12/11/2023 16:32:19  pygeoprocessing.routing.routing INFO     (extract_strahler_streams_d8): flow accumulation adjustment complete
12/11/2023 16:32:19  pygeoprocessing.routing.routing INFO     (extract_strahler_streams_d8): final pass on stream order and geometry
12/11/2023 16:32:19  pygeoprocessing.routing.routing INFO     (extract_strahler_streams_d8): final pass on stream order complete
12/11/2023 16:32:19  pygeoprocessing.routing.routing INFO     (extract_strahler_streams_d8): commit transaction due to stream joining
12/11/2023 16:32:19  pygeoprocessing.routing.routing INFO     (extract_strahler_streams_d8): all done
12/11/2023 16:32:20  taskgraph.Task     ERROR    Something went wrong when adding task Calculate subwatersheds from stream order (6), terminating taskgraph.
Traceback (most recent call last):
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\taskgraph\Task.py", line 674, in add_task
    new_task._call()
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\taskgraph\Task.py", line 1093, in _call
    payload = self._func(*self._args, **self._kwargs)
  File "src\pygeoprocessing\routing\routing.pyx", line 4099, in pygeoprocessing.routing.routing.calculate_subwatershed_boundary
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
12/11/2023 16:32:20  natcap.invest.utils ERROR    Exception while executing natcap.invest.routedem
Traceback (most recent call last):
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\natcap\invest\utils.py", line 164, in prepare_workspace
    yield
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\natcap\invest\cli.py", line 470, in main
    model_module.execute(parsed_datastack.args)
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\natcap\invest\routedem.py", line 485, in execute
    graph.add_task(
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\taskgraph\Task.py", line 674, in add_task
    new_task._call()
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\taskgraph\Task.py", line 1093, in _call
    payload = self._func(*self._args, **self._kwargs)
  File "src\pygeoprocessing\routing\routing.pyx", line 4099, in pygeoprocessing.routing.routing.calculate_subwatershed_boundary
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
12/11/2023 16:32:20  natcap.invest.utils INFO     Elapsed time: 2.31s
12/11/2023 16:32:20  natcap.invest.utils INFO     Execution finished
Traceback (most recent call last):
  File "C:\Users\dmf\projects\invest\env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dmf\projects\invest\env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\dmf\projects\invest\env\Scripts\invest.exe\__main__.py", line 7, in <module>
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\natcap\invest\cli.py", line 470, in main
    model_module.execute(parsed_datastack.args)
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\natcap\invest\routedem.py", line 485, in execute
    graph.add_task(
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\taskgraph\Task.py", line 674, in add_task
    new_task._call()
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\taskgraph\Task.py", line 1093, in _call
    payload = self._func(*self._args, **self._kwargs)
  File "src\pygeoprocessing\routing\routing.pyx", line 4099, in pygeoprocessing.routing.routing.calculate_subwatershed_boundary
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by davemfish** [comment]
This exception arises from an empty feature in the strahler stream order vector created by `routing.extract_strahler_streams_d8`.

`_calculate_stream_geometry` might be returning `None`. In one case (routing.pyx: 3668) that is caught by deleting the stream feature, but in another (routing.pyx: 3430), the feature is not deleted, only skipped. So this is likely an issue for pygeoprocessing. I don't think I know enough yet to know if deleting the feature would be appropriate, or if the empty geometry is the sign of a larger problem.

**Comment by davemfish** [comment]
`_calculate_stream_geometry` is inadvertently being given a seed point that is over `nodata` for all the relevant rasters.

These "seed points" are meant to be Stream Connectivity Points, in other words,
```
    # First pass - search for bifurcating stream points
    #   look at all pixels in the raster. If a pixel has:
    #       * flow accumulation > threshold and
    #       * more than two upstream neighbors with
    #         flow accumulation > threshold or
    #       * drains to edge or nodata pixel
    #   record a seed point for that bifurcation for later processing.
```

### in `routing.extract_strahler_streams_d8`
We're getting a false-positive when the local flow accumulation value is the `nodata` value, which overflows the `long` variable where it's being stored.

All valid values in the flow accumulation raster are integers, and the `min_flow_accumulation_threshold` parameter is a `long`. But reading `flow_accumulation_d8()` it seems clear there was a deliberate choice to make the target datatype a 64-bit float. So it seems like we need to check for a `double` nodata, but everywhere else we could be still be using `longs`.
