### ISSUE TITLE
`reproject_vector` fails on non-UTF-8 strings

### ISSUE THREAD

**Issue by davemfish** [natcap/pygeoprocessing#418]
I have an example shapefile that raises this exception:

```python
Traceback (most recent call last):
  File "C:\Users\dmf\projects\pygeoprocessing\scratch\reproject_vector.py", line 8, in <module>
    pygeoprocessing.reproject_vector(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        base_vector_path, base_wkt,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        '../forum/ndr_setfield/copy.shp',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        driver_name='ESRI Shapefile')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\\pygeoprocessing\\geoprocessing_core.pyx", line 77, in pygeoprocessing.geoprocessing_core.gdal_use_exceptions.wrapper
    with GDALUseExceptions():
  File "src\\pygeoprocessing\\geoprocessing_core.pyx", line 78, in pygeoprocessing.geoprocessing_core.gdal_use_exceptions.wrapper
    return func(*args, **kwargs)
  File "C:\Users\dmf\projects\pygeoprocessing\src\pygeoprocessing\geoprocessing.py", line 2282, in reproject_vector
    target_feature.SetField(target_index, value)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmf\projects\pygeoprocessing\env\Lib\site-packages\osgeo\ogr.py", line 3877, in SetField
    return _ogr.Feature_SetFieldString(self, fld_index, args[1])
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: not a string or os.PathLike
```

I think GDAL tried to read a string assuming a UTF8 encoding during a `GetField` call, and then the result is not usable in `SetField`. 

`layer.TestCapability(ogr.OLCStringsAsUTF8))` returns `False` for this layer.

We could simply wrap the `SetField` call in `reproject_vector` in a `try/except`. And then maybe replace offending characters with something else.

**Comment by emlys** [comment]
to clarify, the string in question is a field name?

**Comment by davemfish** [comment]
> to clarify, the string in question is a field name?

It's actually the field value.
